### ISSUE TITLE
Error when calling CancerDetector function

### ISSUE THREAD

**Issue by jeffsun905** [jasminezhoulab/cfTools#7]
When I was testing the included test data, I got the following errors for the function (all previous functions are ok). It appears the conda environment related?
CancerDetector(fragMethFile, markerParamFile)
Traceback (most recent call last):
  File "/home/cfTools/python/CalcReadLikelihood.py", line 10, in <module>
    from scipy.special import gamma
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "/home/cfTools/python/CancerDetector.py", line 10, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by RoseHuRan** [comment]
cfTools uses the package basilisk to manage running python code, which will create a Conda environment. Please make sure that the basilisk library is installed.

**Comment by jeffsun905** [comment]
yes it was installed and can be loaded.

**Comment by RoseHuRan** [comment]
It seems that the Conda environment has not been created successfully. I apologize that I cannot figure it out without the complete information about the error message and the steps you took.

If you can read the CancerDetector.R code in the Github R folder, you can find that it just run two python scripts: CalcReadLikelihood.py and CancerDetector.py in the inst/python folder. You can try directly running these two python scripts with the input data.
